variable "rgvar" {}
variable "vnetvar" {}
variable "subnetvar" {}
variable "pipvar" {}
variable "nicvar" {}
variable "linuxvm_var" {}
variable "nsgvar" {}
variable "nsrvar" {}
variable "subansgvar" {}
variable "bastionvar" {}