name: Terraform Azure Workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Verify Azure Login
      - name: Verify Azure Login
        run: |
          echo "Azure Login Successful!"
          az account show

      # 4. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 5. Terraform Version
      - name: Terraform Version
        run: terraform version

      # 6. Terraform Init
      - name: Terraform Init
        working-directory: parent_module/dev
        run: terraform init

      # 7. Terraform Validate
      - name: Terraform Validate
        working-directory: parent_module/dev
        run: terraform validate

      # 8. Terraform Plan
      - name: Terraform Plan
        working-directory: parent_module/dev
        run: terraform plan